"""openrein C++ core type stubs (PEP 561)."""
from typing import Any, Callable, Dict, List, Optional, Union

class Engine:
    """LLM agent engine — message state + tool_use execution loop."""

    def __init__(
        self,
        system_prompt: str = "",
        tools: Union[bool, List[Dict[str, Any]]] = True,
    ) -> None: ...

    def add(self, role: str, content: Any) -> None: ...
    def step(self, content: Any) -> bool: ...
    def reset(self) -> None: ...

    def tool(
        self,
        name: str,
        description: str,
        *,
        schema: Optional[Dict[str, Any]] = None,
    ) -> Callable: ...

    def register_tool(
        self,
        func: Callable,
        *,
        name: str,
        description: str,
        schema: Optional[Dict[str, Any]] = None,
    ) -> None: ...

    def tool_schemas(self, include_builtins: bool = True) -> List[Dict[str, Any]]: ...
    def add_subagent(self, name: str, subagent: "SubAgent") -> None: ...
    def active_subagents(self) -> List["SubAgent"]: ...
    def add_mcp_server(
        self,
        name: str,
        command_or_url: Union[List[str], str],
    ) -> None:
        """Connect to an MCP server.

        Args:
            name: identifier for the server
            command_or_url: list[str] → stdio (spawns a process),
                            str       → HTTP (JSON-RPC POST to URL)
        """
        ...
    def set_messages(self, messages: List[Dict[str, Any]]) -> None: ...
    def maybe_compact(self, model_fn: Callable, threshold: int = 80000) -> bool: ...
    def on_subagent_done(self, tool_use_id: str, result: str) -> None: ...

    @property
    def system_prompt(self) -> str: ...
    @system_prompt.setter
    def system_prompt(self, value: str) -> None: ...

    @property
    def messages(self) -> List[Dict[str, Any]]: ...
    @messages.setter
    def messages(self, value: List[Dict[str, Any]]) -> None: ...

    @property
    def done(self) -> bool: ...
    @property
    def last_answer(self) -> Optional[str]: ...
    @property
    def tool_names(self) -> List[str]: ...

    def __repr__(self) -> str: ...


class SubAgent:
    """Developer-defined sub-agent."""

    def __init__(self, description: str, model: Callable) -> None: ...

    def step(self, content: Any) -> bool: ...
    def reset(self) -> None: ...

    def tool(
        self,
        name: str,
        description: str,
        *,
        schema: Optional[Dict[str, Any]] = None,
    ) -> Callable: ...

    def register_tool(
        self,
        func: Callable,
        *,
        name: str,
        description: str,
        schema: Optional[Dict[str, Any]] = None,
    ) -> None: ...

    def tool_schemas(self) -> List[Dict[str, Any]]: ...
    def is_running(self) -> bool: ...

    @property
    def messages(self) -> List[Dict[str, Any]]: ...
    @property
    def messages_with_system(self) -> List[Dict[str, Any]]: ...
    @property
    def description(self) -> str: ...
    @property
    def system_prompt(self) -> str: ...
    @property
    def model(self) -> Callable: ...
    @property
    def last_answer(self) -> Optional[str]: ...

    def __repr__(self) -> str: ...


class Compact:
    """Context compaction utility."""

    def __init__(self) -> None: ...
    def estimate_tokens(self, messages: List[Dict[str, Any]]) -> int: ...
    def should_compact(self, messages: List[Dict[str, Any]], threshold: int = 80000) -> bool: ...
    def make_prompt(self, messages: List[Dict[str, Any]]) -> str: ...
    def parse_response(self, response_text: str) -> str: ...
    def apply(self, messages: List[Dict[str, Any]], summary: str) -> List[Dict[str, Any]]: ...


def default_tools() -> List[Dict[str, Any]]:
    """Return schemas for the 8 built-in tools (Read/Write/Edit/Bash/Grep/Glob/WebFetch/WebSearch)."""
    ...


__version__: str
